---
AWSTemplateFormatVersion: "2010-09-09"
Description: "sample-aws-CFn-S3 template"

Parameters:
  BucketName:
    Description: S3 bucket name.
    Type: String

Resources:
  SampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 1
